# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Install any necessary dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    libssl-dev \
    nodejs

# Install Rust, update to the latest version, and build tree-sitter
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . $HOME/.cargo/env && \
    rustup update && \
    git clone https://github.com/tree-sitter/tree-sitter.git && \
    cd tree-sitter && \
    git checkout $(git describe --tags `git rev-list --tags --max-count=1`) && \
    cargo build --release && \
    cp target/release/tree-sitter /usr/local/bin/

# Clone and build tree-sitter grammars
RUN git clone https://github.com/tree-sitter/tree-sitter-python && \
    cd tree-sitter-python && \
    tree-sitter generate

RUN git clone https://github.com/tree-sitter/tree-sitter-javascript && \
    cd tree-sitter-javascript && \
    tree-sitter generate

# Clone your project's repository
RUN git clone https://github.com/odegay/sonar-gpt-fixes && \
    cd sonar-gpt-fixes && \
    git checkout 4000_tokens && \
    cd gptscripts/python && \
    pip install --no-cache-dir -r requirements.txt

# Change working directory to your project's directory
WORKDIR /app/sonar-gpt-fixes/gptscripts/python/debugfiles

# Run the command to start your application
CMD ["python", "code_analyzer_test.py"]